---
ansible_host: 10.100.50.133
ansible_network_os: eos

l3_interfaces:
  - name: Ethernet2
    description: Link to Spine1
    ipv4: 172.16.36.14/31
    enable: yes
  - name: Ethernet3
    description: Link to Spine2
    ipv4: 172.16.36.16/31
    enable: yes
  - name: Loopback0
    description: Loopback0
    ipv4: 172.16.0.6/32
  - name: Loopback1
    description: Loopback1
    ipv4: 172.16.0.56/32
...